openapi: 3.0.0
info:
  title: device
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /device/report:
    get:
      summary: Return a report
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./device-report/models/report.v1.yaml
      operationId: get-device-report
      parameters:
        - schema:
            type: string
          in: query
          name: report_number
        - schema:
            type: string
          in: query
          name: imei
        - schema:
            type: string
          in: query
          name: start_datetime
        - schema:
            type: string
          in: query
          name: end_datetime
components:
  schemas: {}
