openapi: 3.0.0
info:
  title: Gateway Service
  version: '1.0'
  contact:
    name: Brent Whitney
    email: bwhitney@phillipsind.com
  description: 'Gateway data is sent constantly to our cloud, processed and stored in our system. This API provided secure access to customers and partners to access this data.'
servers:
  - url: 'http://localhost:3000'
paths:
  /gateway/reports:
    get:
      summary: Gateway report data
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./device-report/models/report.v1.yaml
      operationId: get-device-report
      parameters:
        - schema:
            type: string
          in: query
          name: gateway_id
          description: typically the imei number
        - schema:
            type: string
            enum:
              - SEQUENCE
              - DATETIME
          in: query
          name: query_method
          description: ''
        - schema:
            type: string
          in: query
          name: from
          description: 'from: [datetime or gateway_sequence_number]'
        - schema:
            type: integer
          in: query
          name: to
          description: 'to: [either datetime or gateway_sequence_number]'
      description: Allows customers to retrieve gateway and sensor data
      tags:
        - Gateway
    parameters: []
components:
  schemas: {}
  securitySchemes:
    API Key - 1:
      name: API Key
      type: apiKey
      in: query
tags:
  - name: Gateway
