openapi: 3.0.0
info:
  title: Device Report
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/reports/{imei}':
    parameters:
      - schema:
          type: string
        name: imei
        in: path
        required: true
    get:
      summary: Return reports based on IMEI
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/report.v1.yaml
            application/xml:
              schema:
                $ref: ./models/report.v1.yaml
      parameters:
        - schema:
            type: integer
          in: query
          name: report_id
components:
  schemas: {}
  securitySchemes:
    API Key - 1:
      name: API Key
      type: apiKey
      in: query
